---
- name: Configure wpa_supplicant
  template:
    src: wpa_supplicant.conf.j2
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
    backup: yes

- name: Turning off WiFi
  shell: rfkill block wifi

- name: Disconnecting from WiFi
  shell: wpa_cli -i wlan0 reconfigure