---
- name: Pulling Docker image from local
  become: no
  delegate_to: localhost
  shell:
    chdir: ../..
    cmd: "AWS_ACCOUNT_ID={{ aws_account_id }} ./pull.sh"
  register: command_output

- debug:
    var: command_output.stdout_lines

- name: Create temporary directory on local for docker image
  become: no
  delegate_to: localhost
  tempfile:
    state: directory
    suffix: jig-app
  register: temp_image_dir

- name: Saving Docker image as .tar
  become: no
  delegate_to: localhost
  shell:
    cmd: "docker save -o {{ temp_image_dir.path }}/pulse-jig.tar pulse-jig"

- name: Copying image over to RPi
  become: no
  copy:
    src: "{{ temp_image_dir.path }}/pulse-jig.tar"
    dest: "{{ app_dir }}"

- name: Loading the copied Docker image
  become: no
  shell:
    cmd: "docker load -i {{ app_dir }}/pulse-jig.tar"
