---
- name: reboot pi
  shell: "sleep 5 && reboot"
  async: 5
  poll: 0
  ignore_errors: true

- name: wait for reboot to finish
  local_action: wait_for host={{ hostname }} state=started port=22 delay=50 timeout=120
  become: false