from typing import Any

str: Any

class GPIOZeroError(Exception): ...
class DeviceClosed(GPIOZeroError): ...
class BadEventHandler(GPIOZeroError, ValueError): ...
class BadWaitTime(GPIOZeroError, ValueError): ...
class BadQueueLen(GPIOZeroError, ValueError): ...
class BadPinFactory(GPIOZeroError, ImportError): ...
class ZombieThread(GPIOZeroError, RuntimeError): ...
class CompositeDeviceError(GPIOZeroError): ...
class CompositeDeviceBadName(CompositeDeviceError, ValueError): ...
class CompositeDeviceBadOrder(CompositeDeviceError, ValueError): ...
class CompositeDeviceBadDevice(CompositeDeviceError, ValueError): ...
class EnergenieSocketMissing(CompositeDeviceError, ValueError): ...
class EnergenieBadSocket(CompositeDeviceError, ValueError): ...
class SPIError(GPIOZeroError): ...
class SPIBadArgs(SPIError, ValueError): ...
class SPIBadChannel(SPIError, ValueError): ...
class SPIFixedClockMode(SPIError, AttributeError): ...
class SPIInvalidClockMode(SPIError, ValueError): ...
class SPIFixedBitOrder(SPIError, AttributeError): ...
class SPIFixedSelect(SPIError, AttributeError): ...
class SPIFixedWordSize(SPIError, AttributeError): ...
class SPIFixedRate(SPIError, AttributeError): ...
class SPIInvalidWordSize(SPIError, ValueError): ...
class GPIODeviceError(GPIOZeroError): ...
class GPIODeviceClosed(GPIODeviceError, DeviceClosed): ...
class GPIOPinInUse(GPIODeviceError): ...
class GPIOPinMissing(GPIODeviceError, ValueError): ...
class InputDeviceError(GPIODeviceError): ...
class OutputDeviceError(GPIODeviceError): ...
class OutputDeviceBadValue(OutputDeviceError, ValueError): ...
class PinError(GPIOZeroError): ...
class PinInvalidFunction(PinError, ValueError): ...
class PinInvalidState(PinError, ValueError): ...
class PinInvalidPull(PinError, ValueError): ...
class PinInvalidEdges(PinError, ValueError): ...
class PinInvalidBounce(PinError, ValueError): ...
class PinSetInput(PinError, AttributeError): ...
class PinFixedPull(PinError, AttributeError): ...
class PinEdgeDetectUnsupported(PinError, AttributeError): ...
class PinUnsupported(PinError, NotImplementedError): ...
class PinSPIUnsupported(PinError, NotImplementedError): ...
class PinPWMError(PinError): ...
class PinPWMUnsupported(PinPWMError, AttributeError): ...
class PinPWMFixedValue(PinPWMError, AttributeError): ...
class PinUnknownPi(PinError, RuntimeError): ...
class PinMultiplePins(PinError, RuntimeError): ...
class PinNoPins(PinError, RuntimeError): ...
class PinInvalidPin(PinError, ValueError): ...
class GPIOZeroWarning(Warning): ...
class DistanceSensorNoEcho(GPIOZeroWarning): ...
class SPIWarning(GPIOZeroWarning): ...
class SPISoftwareFallback(SPIWarning): ...
class PWMWarning(GPIOZeroWarning): ...
class PWMSoftwareFallback(PWMWarning): ...
class PinWarning(GPIOZeroWarning): ...
class PinFactoryFallback(PinWarning): ...
class NativePinFactoryFallback(PinWarning): ...
class PinNonPhysical(PinWarning): ...
class ThresholdOutOfRange(GPIOZeroWarning): ...
class CallbackSetToNone(GPIOZeroWarning): ...
class AmbiguousTone(GPIOZeroWarning): ...
