from .devices import Device as Device
from .exc import DeviceClosed as DeviceClosed, InputDeviceError as InputDeviceError, SPIBadChannel as SPIBadChannel
from typing import Any

str: Any

class SPIDevice(Device):
    def __init__(self, **spi_args) -> None: ...
    def close(self) -> None: ...
    @property
    def closed(self): ...

class AnalogInputDevice(SPIDevice):
    def __init__(self, bits, max_voltage: float = ..., **spi_args) -> None: ...
    @property
    def bits(self): ...
    @property
    def value(self): ...
    @property
    def raw_value(self): ...
    @property
    def max_voltage(self): ...
    @property
    def voltage(self): ...

class MCP3xxx(AnalogInputDevice):
    def __init__(
        self, channel: int = ..., bits: int = ..., differential: bool = ..., max_voltage: float = ..., **spi_args
    ) -> None: ...
    @property
    def channel(self): ...
    @property
    def differential(self): ...

class MCP3xx2(MCP3xxx): ...

class MCP30xx(MCP3xxx):
    def __init__(self, channel: int = ..., differential: bool = ..., max_voltage: float = ..., **spi_args) -> None: ...

class MCP32xx(MCP3xxx):
    def __init__(self, channel: int = ..., differential: bool = ..., max_voltage: float = ..., **spi_args) -> None: ...

class MCP33xx(MCP3xxx):
    def __init__(self, channel: int = ..., differential: bool = ..., max_voltage: float = ..., **spi_args) -> None: ...
    @property
    def differential(self): ...
    @property
    def value(self): ...

class MCP3001(MCP30xx):
    def __init__(self, max_voltage: float = ..., **spi_args) -> None: ...

class MCP3002(MCP30xx, MCP3xx2):
    def __init__(self, channel: int = ..., differential: bool = ..., max_voltage: float = ..., **spi_args) -> None: ...

class MCP3004(MCP30xx):
    def __init__(self, channel: int = ..., differential: bool = ..., max_voltage: float = ..., **spi_args) -> None: ...

class MCP3008(MCP30xx):
    def __init__(self, channel: int = ..., differential: bool = ..., max_voltage: float = ..., **spi_args) -> None: ...

class MCP3201(MCP32xx):
    def __init__(self, max_voltage: float = ..., **spi_args) -> None: ...

class MCP3202(MCP32xx, MCP3xx2):
    def __init__(self, channel: int = ..., differential: bool = ..., max_voltage: float = ..., **spi_args) -> None: ...

class MCP3204(MCP32xx):
    def __init__(self, channel: int = ..., differential: bool = ..., max_voltage: float = ..., **spi_args) -> None: ...

class MCP3208(MCP32xx):
    def __init__(self, channel: int = ..., differential: bool = ..., max_voltage: float = ..., **spi_args) -> None: ...

class MCP3301(MCP33xx):
    def __init__(self, max_voltage: float = ..., **spi_args) -> None: ...

class MCP3302(MCP33xx):
    def __init__(self, channel: int = ..., differential: bool = ..., max_voltage: float = ..., **spi_args) -> None: ...

class MCP3304(MCP33xx):
    def __init__(self, channel: int = ..., differential: bool = ..., max_voltage: float = ..., **spi_args) -> None: ...
