from .exc import ZombieThread as ZombieThread
from threading import Thread
from typing import Any

str: Any

class GPIOThread(Thread):
    stopping: Any
    daemon: bool
    def __init__(self, target, args=..., kwargs: Any | None = ..., name: Any | None = ...) -> None: ...
    def start(self) -> None: ...
    def stop(self, timeout: int = ...) -> None: ...
    def join(self, timeout: Any | None = ...) -> None: ...
