---
app:
  test_firmware_path: firmware/test-firmware.bin
  prod_firmware_path: firmware/prod-firmware.bin
  skip_firmware_load: false
  hwspec_repair_mode: false
device:
  minter_id: 0xff
  thing_type_name: TA3K
  thing_type_id: 0x201
  hw_revision: r2.0
  assembly_id: 0x00
  assembly_version: 0.0.0
  manufacturer_name: Woodside
  manufacturer_id: 0x01
  iecex_cert: Not set
mode_vars:
  cable_lengths: [1.5, 2.0]
api:
  region: ap-southeast-2
  host: https://8k3h1lqdjd.execute-api.ap-southeast-2.amazonaws.com
  stage: dev
lora:
  test:
    sub_band: 7
    join_eui: aa:aa:aa:aa:aa:aa:aa:aa
    app_key: aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa
  config:
    join_eui: aa:aa:aa:aa:aa:aa:aa:aa
network:
  ping_interval: 30 # in seconds
