from qrcode import constants as constants
from typing import Any

EXP_TABLE: Any
LOG_TABLE: Any
RS_BLOCK_OFFSET: Any
RS_BLOCK_TABLE: Any

def glog(n): ...
def gexp(n): ...

class Polynomial:
    num: Any
    def __init__(self, num, shift) -> None: ...
    def __getitem__(self, index): ...
    def __iter__(self): ...
    def __len__(self): ...
    def __mul__(self, other): ...
    def __mod__(self, other): ...

class RSBlock:
    total_count: Any
    data_count: Any
    def __init__(self, total_count, data_count) -> None: ...

def rs_blocks(version, error_correction): ...
