import qrcode.image.base
from typing import Any

class PilImage(qrcode.image.base.BaseImage):
    kind: str
    fill_color: Any
    def new_image(self, **kwargs): ...
    def drawrect(self, row, col) -> None: ...
    def save(self, stream, format: Any | None = ..., **kwargs) -> None: ...
    def __getattr__(self, name): ...
