import qrcode.image.base
from typing import Any

class SvgFragmentImage(qrcode.image.base.BaseImage):
    kind: str
    allowed_kinds: Any
    unit_size: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def drawrect(self, row, col) -> None: ...
    def units(self, pixels, text: bool = ...): ...
    def save(self, stream, kind: Any | None = ...) -> None: ...
    def to_string(self): ...
    def new_image(self, **kwargs): ...

class SvgImage(SvgFragmentImage):
    background: Any

class SvgPathImage(SvgImage):
    QR_PATH_STYLE: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def drawrect(self, row, col) -> None: ...
    def make_path(self): ...
    def to_string(self): ...

class SvgFillImage(SvgImage):
    background: str

class SvgPathFillImage(SvgPathImage):
    background: str
