---
- name: Disabling first run wizard
  file:
    state: absent
    path: /etc/xdg/autostart/piwiz.desktop

- name: Disabling removable media autorun
  lineinfile:
    path: /home/pi/.config/pcmanfm/LXDE-pi/pcmanfm.conf
    regexp: '^autorun='
    line: autorun=0

- name: Disabling screen blanking
  template:
    src: 10-blanking.conf
    dest: /etc/X11/xorg.conf.d/10-blanking.conf
    backup: yes
