from serial.serialutil import *
from typing import Any

def my_import(name): ...
def detect_java_comm(names): ...

comm: Any

def device(portnumber): ...

class Serial(SerialBase):
    sPort: Any
    is_open: bool
    def open(self) -> None: ...
    def close(self) -> None: ...
    @property
    def in_waiting(self): ...
    def read(self, size: int = ...): ...
    def write(self, data): ...
    def reset_input_buffer(self) -> None: ...
    def reset_output_buffer(self) -> None: ...
    def send_break(self, duration: float = ...) -> None: ...
    @property
    def cts(self) -> None: ...
    @property
    def dsr(self) -> None: ...
    @property
    def ri(self) -> None: ...
    @property
    def cd(self) -> None: ...
