---
- name: Configure wpa_supplicant
  template:
    src: wpa_supplicant.conf.j2
    dest: /etc/wpa_supplicant/wpa_supplicant.conf
    backup: yes

- name: Turning on WiFi
  shell: rfkill unblock wifi

- name: Connecting to WiFi
  shell: wpa_cli -i wlan0 reconfigure