from serial.serialutil import (
    PortNotOpenError as PortNotOpenError,
    SerialBase as SerialBase,
    SerialException as SerialException,
    Timeout as Timeout,
    to_bytes as to_bytes,
)
from typing import Any

class Serial(SerialBase):
    BAUDRATES: Any
    def __init__(self, *args, **kwargs) -> None: ...
    is_open: bool
    def open(self) -> None: ...
    def from_url(self, url): ...
    def close(self) -> None: ...
    @property
    def in_waiting(self): ...
    def reset_input_buffer(self) -> None: ...
    def reset_output_buffer(self) -> None: ...
    def read(self, size: int = ...): ...
    def write(self, data) -> None: ...
