---
- name: Changing hostname 1 of 2
  shell: sed -i 's/{{ ansible_fqdn }}/{{ hostname }}/g' /etc/hosts
  when: hostname | length > 0

- name: Changing hostname 2 of 2
  shell: echo "{{ hostname }}" | tee /etc/hostname
  when: hostname | length > 0
