version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$BUILD_IMAGE_TAG
      - docker image ls
      - docker tag $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$BUILD_IMAGE_TAG $AWS_ACCOUNT_ID_TARGET.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker image ls

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Assuming role...
      - . ./ci/scripts/assume-role.sh
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID_TARGET.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID_TARGET.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG