---
- name: Create app directory
  become_user: pi
  file:
    path: "{{ app_dir }}"
    state: directory

- name: Creating jig app auto launch entry
  template:
    src: jig-app.desktop.j2
    dest: /etc/xdg/autostart/jig-app.desktop

- name: Copying boot scripts
  become_user: pi
  copy:
    src: "{{ item }}"
    dest: "{{ app_dir }}"
    mode: +x
  with_items:
    - ../../run.sh
    - ../../pull.sh
    - ../../boot.sh
