---
- name: Creating firmware directory
  become_user: pi
  file:
    path: "{{ firmware_dir }}"
    state: directory

- name: Copying Firmware(s) to Jig
  become_user: pi
  copy:
    src: "{{ item }}"
    dest: "{{ firmware_dir }}"
  with_items:
    - "../../pulse_jig/firmware/{{ test_firmware }}"
    - "../../pulse_jig/firmware/{{ prod_firmware }}"
