---
- name: Generate policy document
  become: no
  delegate_to: localhost
  template:
    src: ../roles/ssm/templates/SSMService-Trust.json.j2
    dest: SSMService-Trust.json

- name: Create IAM role
  become: no
  delegate_to: localhost
  shell: |
    aws iam create-role \
      --role-name "{{ iam_role_name }}" \
      --assume-role-policy-document file://SSMService-Trust.json \
      --permissions-boundary "{{ permission_boundry_arn }}"

- name: Attach policy to created role
  become: no
  delegate_to: localhost
  shell: |
    aws iam attach-role-policy \
      --role-name "{{ iam_role_name }}" \
      --policy-arn arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore