---
- set_fact:
    postfix: ""

- set_fact:
    postfix: "-{{ copy_id }}"
  when: copy_id | length > 0

- set_fact:
    instance_name: "{{ ansible_fqdn }}{{ postfix }}"

- name: Creating SSM directory in tmp
  become: no
  file:
    path: "{{ temp_ssm }}"
    state: directory

- name: Downloading SSM agent to {{ temp_ssm }}
  become: yes
  get_url:
    url: "{{ ssm_url }}"
    dest: "{{ temp_ssm }}"

- name: Installing SSM agent
  become: yes
  apt:
    deb: /tmp/ssm/amazon-ssm-agent.deb

- name: Creating IAM role
  import_tasks: create_role.yml
  when: create_role | bool

- name: Creating an activation
  import_tasks: activate.yml

- name: Stopping SSM agent
  become: yes
  service:
    name: amazon-ssm-agent
    state: stopped

- name: Registering SSM agent
  become: yes
  shell: amazon-ssm-agent -register -code "{{ ssm_activation_code }}" -id "{{ ssm_activation_id }}" -region "{{ region }}" -y

- name: Starting SSM agent
  become: yes
  service:
    name: amazon-ssm-agent
    state: started

- name: Give it 10 seconds to start SSM agent
  pause:
    seconds: 10
