import codecs
from typing import Any

unicode = str
HEXDIGITS: str

def hex_encode(data, errors: str = ...): ...
def hex_decode(data, errors: str = ...): ...

class Codec(codecs.Codec):
    def encode(self, data, errors: str = ...): ...
    def decode(self, data, errors: str = ...): ...

class IncrementalEncoder(codecs.IncrementalEncoder):
    errors: Any
    state: int
    def __init__(self, errors: str = ...) -> None: ...
    def reset(self) -> None: ...
    def getstate(self): ...
    def setstate(self, state) -> None: ...
    def encode(self, data, final: bool = ...): ...

class IncrementalDecoder(codecs.IncrementalDecoder):
    def decode(self, data, final: bool = ...): ...

class StreamWriter(Codec, codecs.StreamWriter): ...
class StreamReader(Codec, codecs.StreamReader): ...

def getregentry(): ...
