import ctypes
from serial.tools import list_ports_common as list_ports_common
from typing import Any

iokit: Any
cf: Any
kIOMasterPortDefault: int
kCFAllocatorDefault: Any
kCFStringEncodingMacRoman: int
kCFStringEncodingUTF8: int
kUSBVendorString: str
kUSBSerialNumberString: str
io_name_size: int
KERN_SUCCESS: int
kern_return_t = ctypes.c_int
kCFNumberSInt8Type: int
kCFNumberSInt16Type: int
kCFNumberSInt32Type: int
kCFNumberSInt64Type: int

def get_string_property(device_type, property): ...
def get_int_property(device_type, property, cf_number_type): ...
def IORegistryEntryGetName(device): ...
def IOObjectGetClass(device): ...
def GetParentDeviceByType(device, parent_type): ...
def GetIOServicesByType(service_type): ...
def location_to_string(locationID): ...

class SuitableSerialInterface: ...

def scan_interfaces(): ...
def search_for_locationID_in_interfaces(serial_interfaces, locationID): ...
def comports(include_links: bool = ...): ...
