from typing import Any

def numsplit(text): ...

class ListPortInfo:
    device: Any
    name: Any
    description: str
    hwid: str
    vid: Any
    pid: Any
    serial_number: Any
    location: Any
    manufacturer: Any
    product: Any
    interface: Any
    def __init__(self, device, skip_link_detection: bool = ...) -> None: ...
    def usb_description(self): ...
    def usb_info(self): ...
    def apply_usb_info(self) -> None: ...
    def __eq__(self, other): ...
    def __hash__(self): ...
    def __lt__(self, other): ...
    def __getitem__(self, index): ...

def list_links(devices): ...
