---
# Don't update these values
# Use roles/vars/environment_vars.yml to update

# Variables for app.env
app_dir: /home/pi/test-jig
target:
aws_account_id:

# Variables for settings.local.yaml
app:
  test_firmware_path: firmware/test-firmware.bin
  prod_firmware_path: firmware/prod-firmware.bin
  skip_test_firmware_load: false
device:
  minter_id:
  thing_type_name:
  thing_type_id:
  hw_revision:
  assembly_id:
  assembly_version:
  manufacturer_name:
  manufacturer_id:
  cable_lengths: [1.5, 2.0]
api:
  region: ap-southeast-2
  host:
  stage:
lora:
  join_eui: aa:aa:aa:aa:aa:aa:aa:aa
  app_key: aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa:aa
network:
  ping_interval: 30 # in seconds
