---
- name: Initialising Pi for the first time
  hosts: all
  become: yes

  roles:
    - basic-config
    - change-passwords
    - localisation
    - set-hostname
    - install-docker
      
  vars_prompt:

    - name: pi_password
      prompt: Enter a new password for the user 'pi' [leave blank for current]
      private: yes
      confirm: yes

    - name: hostname
      prompt: Enter new hostname [leave blank for current]
      private: no

  post_tasks:
    - name: Rebooting...
      command: echo "Ansible initiated rebooting"
      notify: reboot pi