---
- name: Initialising Pi for the first time (prod)
  hosts: all
  become: yes

  vars_files:
    - vars/environment_vars.yml

  roles:
    - disable-wifi
    - remove-ssh-key
    - disable-password-auth
    - env-config
    - app-launch
    - update-firmware
