---
- name: Environment config, and update packages, firmwares and the jig app
  hosts: all
  become: yes

  vars_files:
    - vars/environment_vars.yml

  roles:
    - env-config
    - app-launch
    - upgrade
    - update-firmware
    - docker-pull
