---
- name: Update all packages to their latest version
  apt:
    force_apt_get: yes
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages
  apt:
    upgrade: safe
    force_apt_get: yes
